export {
    BAUD_RATES,
    DATA_BITS,
    STOP_BITS,
    PARITY_OPTIONS,
    FLOW_CONTROL_OPTIONS,
    DEFAULT_SERIAL_CONFIG,
    THEME_OPTIONS,
    THEME_VARIANTS,
    MAX_TERMINAL_LINES,
    RATE_CALCULATION_INTERVAL,
    TIMESTAMP_FORMAT,
    STORAGE_KEYS
} from '../../../shared/js/constants.js';
